services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
        - flask_interview_pgsql_data:/var/lib/postgresql/data:rw

volumes:
  flask_interview_pgsql_data:
    name: "flask_interview_pgsql_data"
